# Generated by Django 6.0.4 on 2026-05-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='discord_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
