# Generated by Django 6.0.4 on 2026-05-01 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventcategory_and_event_category_fk'),
        ('events', '0006_event_tracker_fk'),
    ]

    operations = [
    ]
